services:
- type: web
  name: mysql
  plan: free
  env: docker
  autoDeploy: false
  
    
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    value: qwerty
  - key: MYSQL_ROOT_PASSWORD
    value: qwerty
